version: "3.8"
services:
  netuno-panel:
    container_name: netuno-panel
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - NEXT_NODE_ENV=prod
    restart: on-failure
    volumes:
      - ".:/app/"
    ports:
      - 80:80
