import type { Metadata } from "next";
import { Inter } from "next/font/google";
//import "./globals.css";
import Menu from "../../components/menu";
import  "../../assets/css/global.css"
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{margin: "unset",background:"#6f9fd51a" /*background:"#8080801a"*/}}>
      
      <div>
        <Menu >
        {children}
        </Menu>
        <div
          style={{
            top: "64px",
            width: "100%",
            minWidth: "360px",
            position: "absolute",
            zIndex: 1,
            backgroundColor: "#000a29",
            borderBottom: "5px solid #7fb300",
          }}
        />
      </div>
      </body>
    </html>

    
  );
}
